[package]
name = "dw_apb_uart"
authors = ["Luoyuan Xiao <xiaoluoyuan@163.com>"]
version = "0.1.0"
edition = "2021"
description = "Uart snps,dw-apb-uart driver in Rust for BST A1000b FADA board."
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/crates/dw_apb_uart"
documentation = "https://arceos-org.github.io/arceos/dw_apb_uart/index.html"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.8"
