[package]
name = "axtask"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
multitask = [ # without the feature, can still use the empty yield_now() and exit()
    "dep:axconfig", "dep:spinlock", "dep:lazy_init",
    "dep:memory_addr", "dep:scheduler",
]

sched_fifo = ["multitask"]
sched_rr = ["multitask"]
default = ["sched_fifo"]

[dependencies]
cfg-if = "1.0"
log = "0.4"
axhal = { path = "../axhal" }
axconfig = { path = "../axconfig", optional = true }
spinlock = { path = "../../crates/spinlock", optional = true }
lazy_init = { path = "../../crates/lazy_init", optional = true }
memory_addr = { path = "../../crates/memory_addr", optional = true }
scheduler = { path = "../../crates/scheduler", optional = true }

[dev-dependencies]
rand = "0.8"
spinlock = { path = "../../crates/spinlock", features = ["std"] }
