[package]
name = "axsync"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS synchronization primitives"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axsync"
documentation = "https://arceos-org.github.io/arceos/axsync/index.html"

[features]
multitask = ["axtask/multitask"]
default = []

[dependencies]
spinlock = { path = "../../crates/spinlock" }
axtask = { path = "../axtask" }

[dev-dependencies]
rand = "0.8"
axsync = { path = ".", features = ["multitask"] }
axtask = { path = "../axtask", features = ["test"] }
