[package]
name = "lazy_init"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "A wrapper for lazy initialized values without concurrency safety but more efficient"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/crates/lazy_init"
documentation = "https://arceos-org.github.io/arceos/lazy_init/index.html"

[dependencies]
