[package]
name = "page_table"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Generic page table structures for various hardware architectures"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/crates/page_table"
documentation = "https://arceos-org.github.io/arceos/page_table/index.html"

[dependencies]
log = "0.4"
memory_addr = { path = "../memory_addr" }
page_table_entry = { path = "../page_table_entry" }
