[package]
name = "arceos-echoserver"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axnet = { path = "../../../modules/axnet" }
axtask = { path = "../../../modules/axtask" }
axerror = { path = "../../../modules/axerror" }
axruntime = { path = "../../../modules/axruntime", features = ["paging", "multitask", "net"] }
