[package]
name = "memory_addr"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Wrappers and helper functions for physical and virtual addresses"
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/arceos/tree/main/crates/memory_addr"
documentation = "https://docs.rs/memory_addr"
keywords = ["arceos", "address", "virtual-memory"]
categories = ["os", "memory-management", "no-std"]

[dependencies]
